-- Seed Scholarships for Veritas and International Opportunities
insert into public.scholarships (title, provider, amount, deadline, university, scope, department_eligibility, link, description)
values 
('Chevening Scholarship', 'UK Government', 'Full Funding', '2024-11-05', 'Multiple UK Universities', 'International', '{"All"}', 'https://www.chevening.org/', 'Fully-funded scholarships to undertake any master''s course at any UK university.'),
('Fulbright Foreign Student Program', 'US Government', 'Full Funding', '2024-10-15', 'Multiple US Universities', 'International', '{"All"}', 'https://foreign.fulbrightonline.org/', 'Enables graduate students, young professionals to study and conduct research in the US.'),
('Gates Cambridge Scholarship', 'Gates Cambridge Trust', 'Full Cost of Study', '2024-12-05', 'University of Cambridge', 'International', '{"All"}', 'https://www.gatescambridge.org/', 'Highly competitive full-cost scholarships for outstanding applicants from countries outside the UK.'),
('Erasmus Mundus Joint Masters', 'European Union', 'Full Funding', '2025-01-15', 'Multiple European Universities', 'International', '{"Computer Science", "Economics", "Engineering"}', 'https://erasmus-plus.ec.europa.eu/', 'Prestigious international study programmes jointly delivered by an international consortium.'),
('Mastercard Foundation Scholars', 'Mastercard Foundation', 'Full Tuition + Living', '2024-11-20', 'University of Oxford', 'International', '{"All"}', 'https://mastercardfdn.org/', 'Provides fully-funded scholarships for bright, emerging African leaders.'),
('DAAD Scholarships', 'German Academic Exchange Service', 'Stipend + Travel', '2024-10-31', 'Multiple German Universities', 'International', '{"Engineering", "Science", "Law"}', 'https://www.daad.de/', 'Funding for postgraduate degrees and research stays in Germany for international students.'),
('Veritas Academic Excellence Award', 'Veritas University', 'Full Tuition', '2024-09-30', 'Veritas University', 'Internal', '{"Computer Science", "Economics", "Law"}', 'https://veritas.edu.ng/scholarships', 'Annual award for top 5% of students in each department.'),
('Federal Government Scholarship', 'FSB Nigeria', '250,000 NGN', '2024-09-15', 'Any Nigerian University', 'National', '{"All"}', 'https://education.gov.ng/fsb/', 'Bilateral education agreement and local federal scholarships for Nigerian students.');
